uint64 timestamp # time since system start (microseconds)
float64[3] position # Latitude, Longitude in degrees positive North and East. Altitude above Mean Sea Level in meters
float32[3] position_stddev # Latitude, longitude and altitude 1 sigma standard deviation in meters
float32[3] velocity # North, East, Down velocity in m.s^-1
float32[3] velocity_stddev # North, East, Down velocity 1 sigma standard deviation in m.s^-1
