#!/bin/sh
#
# @name Generic Standard VTOL
#
# @type Standard VTOL
# @class VTOL

# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 2
param set-default VT_TYPE 2
param set-default MAV_TYPE 22

set MIXER quad_x
set MIXER_AUX vtol_AAERT

set PWM_OUT 1234
