#!/bin/sh
#
# @name Generic VTOL Duo Tailsitter
#
# @type VTOL Tailsitter
# @class VTOL
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 4
param set-default MAV_TYPE 19
param set-default VT_TYPE 0
param set-default VT_ELEV_MC_LOCK 0

set MIXER vtol_tailsitter_duo

set PWM_OUT 1234
